### ISSUE TITLE
Like @charset, @import and @namespace, @property should remain outside of generated layers

### ISSUE THREAD

**Issue by sentience** [web-baseline/postcss-wrap-up-layer#1]
Like `@charset`, `@import` and `@namespace`, `@property` should remain outside of generated layers.

Input:
```css
@property --gradient-angle {
  syntax: "<angle>";
  initial-value: 310deg;
  inherits: false;
}
a {
  width: 100%;
}
```

Current output:
```css
@layer layername {
  @property --gradient-angle {
    syntax: "<angle>";
    initial-value: 310deg;
    inherits: false;
  }
  a {
    width: 100%;
  }
}
```

Expected output:
```css
@property --gradient-angle {
  syntax: "<angle>";
  initial-value: 310deg;
  inherits: false;
}
@layer layername {
  a {
    width: 100%;
  }
}
```
